language: ruby
rbenv:
  - 2.5.3
addons:
  posgresql: 9.6
script:
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: aebdA9NQVYOAPQhp9eRBWI9SNAcid+LsV5HPYEuNCLeXYcML/wU8BfyVaGM/LBKVhSBweUfjAmAXwMxffOVYcKBHibXrNlmiEfW+/b5e/GwRlNoF/+9awzQlGj8J2U5iSMviPcL/Ga1mnBTeL+JJ/Nn39Js9srFtZoi0Y+oPMWLTBEoJntQNXgkoiPUi2EEPIVn1tISGViK+xG9KwnjqdSkxd4Gx9hGbM5K17DOHrAF0r6PgSKpmisexyxMbKZRMC3n8UwbDrfgGLI3lrJf9mZmOZ3JeI8MPuRS7eEFGAX4pyhcS2a4igt4aKjAondVyS0p4rRn7tfEBpWoF4IZB7RFap6lLOHP7fXhcow6FRDgCvu+My5IBv2LxeKXrzTPVxP0uJVoQ989t49P2P0+2YGZEWgYMl4Ct0TFFYmha/zuwdPl3YCchG34Z+TPmNJ/6vcY+wZ7EbE4jy7Fc11KaqFHaQUSGmQyaf09DGu6hBbkczl2rXD2hriol2J6PdSujZt1mCoxBKYmZaKNau3WyybhkRQA4ztY2iViGXPMTNJ4VwY5uc9HqgmUy65hdfEO3Jsk/ho5kuva77yTFvUIlIb/uT77cnYTllveHz67n2Dl8KrAnG7U/S/uhpgUxA257EKIBDN9bFWZaLP4NPzAPybQyz/O8IhzRdEab5xNJFGY=
  skip_cleanup: true
  on:
    all_branches: true
  app: sweater-weather-final
